<?php

namespace Tests\Feature;

use App\Models\Reply;
use App\Models\Thread;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class ThreadTest extends TestCase
{
    use DatabaseMigrations;

    protected $thread;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = Thread::factory()->create();

    }

    function test_a_thread_has_replies(){

        $this->assertInstanceOf(Collection::class, $this->thread->replies);
    }

    function test_a_thread_has_a_creator(){
        $this->assertInstanceOf(User::class, $this->thread->creator);
    }

    function test_a_thread_can_add_a_reply(){

        $this->thread->addReply([
            'body' => 'FooBar',
            'user_id' => 1
        ]);

        $this->assertCount(1, $this->thread->replies );
    }
}
